# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-05753c51-d554-4eff-b4a0-ef1d56701f75";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks-05753c51-d554-4eff-b4a0-ef1d56701f75".device = "/dev/disk/by-uuid/05753c51-d554-4eff-b4a0-ef1d56701f75";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1A3C-6EED";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-23674279-8e3c-45f7-95bc-15a4141f2784";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-23674279-8e3c-45f7-95bc-15a4141f2784".device = "/dev/disk/by-uuid/23674279-8e3c-45f7-95bc-15a4141f2784";

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
